sudo: false
language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -U pip setuptools tox-travis codecov pre-commit
script:
  - tox
  - pre-commit run --all-files
after_success:
  - codecov
